### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zlx-6** [wuyuebupt/doubleheadsrcnn#2]
hi， I don't know if I understand it wrong：i want to know why should  expand the proposals when regression.

**Comment by wuyuebupt** [comment]
Hi, thanks for insterested in our work. We found that expanding the proposals for regression could improve the results. We conjecture that pooling from expanded proposals may extract more context features than from original proposals.

**Comment by zlx-6** [comment]
OK, thanks for your answers
