### ISSUE TITLE
Where is Double-Head-Ext

### ISSUE THREAD

**Issue by wangjue-wzq** [wuyuebupt/doubleheadsrcnn#3]
Hi！I can‘t find where is Double-Head-Ext.

**Comment by wuyuebupt** [comment]
@wangjue-wzq Double-Head-Ext is generalized from Double-Head. You can set the  "--mask-loss 0.5 2.0 1.4 0.6" in the file "train_cmd.sh" to train a Double-Head-Ext model.

**Comment by wangjue-wzq** [comment]
OK！Thanks！
