### ISSUE TITLE
Double-Head-Ext 

### ISSUE THREAD

**Issue by zlx-6** [wuyuebupt/doubleheadsrcnn#6]
Hi, i only find code about the Double-Head in mmdetection, and i can not find the code about the  "Extension: Leveraging Unfocused Tasks" in the paper. so i want to know if you  achieve the Double-Head-Ext in the mmdetection.

**Comment by wuyuebupt** [comment]
@zlx-6 Thanks for interested in our work. No, we haven't finished the double-head-ext in mmdetection. You can refer this repo for the implementaion of double-head-ext.

**Comment by zlx-6** [comment]
thank you for your reply.
